#FROM mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04
FROM mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
RUN apt-get update -y
#RUN sudo apt-get update -y
RUN apt-get install -y python3.8
RUN whereis python3.8
RUN whereis python3.8

ENV PYTHONPATH "${PYTHONPATH}:/usr/bin/python3.8"
RUN apt-get install -y python3.8-venv
RUN echo "Hello from custom container!"

RUN python -m venv /opt/venv

RUN /opt/venv/bin/pip install --upgrade pip
RUN /opt/venv/bin/pip install wheel
RUN /opt/venv/bin/pip install azureml-defaults
RUN /opt/venv/bin/pip install gunicorn
#RUN /opt/venv/bin/pip install torch

#COPY . /app
#RUN /opt/venv/bin/pip install -e /app


#CMD ["/opt/venv/bin/python","app/src/main.py","--train"]